update city_address_attributes set neighborhood = 'Bannister Acres' where neighborhood = 'Bannister Ares';
update city_address_attributes set neighborhood = 'Birdlespur' where neighborhood = 'Birdlespur';
update city_address_attributes set neighborhood = 'Blenheim Square Research Hospital' where neighborhood = 'Bleheim Square-Research Hospital';
update city_address_attributes set neighborhood = 'Boone Hills' where neighborhood = 'Bonne Hills';
update city_address_attributes set neighborhood = 'Central Blue Valley And Park Tower Gardens' where neighborhood = 'Central Blue Valley-Park Tower Grade';
update city_address_attributes set neighborhood = 'East Swope Highlands' where neighborhood = 'East Sqope Highlands';
update city_address_attributes set neighborhood = 'Eastwood Hills East' where neighborhood = 'Eastwood Hill East';
update city_address_attributes set neighborhood = 'Fairway Hills' where neighborhood = 'Faireway Hills';
update city_address_attributes set neighborhood = 'Independence Plaza' where neighborhood = 'Indipendence Plaza';
update city_address_attributes set neighborhood = 'Linwood Homeowners-Ivanhoe' where neighborhood = 'Linwood Homeowner-Ivanhoe';
update city_address_attributes set neighborhood = 'Little Blue' where neighborhood = 'Little Blue Valley';
update city_address_attributes set neighborhood = 'Marlborough Heights/Marlborough Pride' where neighborhood = 'Marlborough Heights-Marlborough Pride';
update city_address_attributes set neighborhood = 'Noble And Gregory Ridge' where neighborhood = 'Norble And Gregory Ridge';
update city_address_attributes set neighborhood = 'Northeast Industrial District' where neighborhood = 'Northest Industrial District';
update city_address_attributes set neighborhood = 'North Indian Mound' where neighborhood = 'North India Mound';
update city_address_attributes set neighborhood = 'Red Bridge South' where neighborhood = 'Red Ridge South';
update city_address_attributes set neighborhood = 'St Catherines Gardens' where neighborhood = 'Saint Catherine''s Gardens';
update city_address_attributes set neighborhood = 'Scarritt Point' where neighborhood = 'Sarritt Point';
update city_address_attributes set neighborhood = 'South Indian Mound' where neighborhood = 'South India Mound';
update city_address_attributes set neighborhood = 'Stratford Estates' where neighborhood = 'Stanford Estates';
update city_address_attributes set neighborhood = 'Stratford Gardens' where neighborhood = 'Stanford Gardens';
update city_address_attributes set neighborhood = 'Washington Wheatley' where neighborhood = 'Washington Weatley';
update city_address_attributes set neighborhood = 'Western Blue Township' where neighborhood = 'West Blue Township';