#!/bin/sh
#
# Will need to extract 
#

SCRIPT_PATH=`dirname $0`

#
# Create a Foreign Data Wrapper to connect to the CSV file
#
SQL=$(cat <<EOF
--
-- Drop just in case
--
DROP FOREIGN TABLE jackson_county_delinquent_tax_parcels; 
DROP SERVER myserver;
--
-- Create
--
CREATE SERVER myserver
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource '/tmp/DelinquencyDataRequest-27-Apr-2018.xlsx',
                         format 'XLSX' );

CREATE FOREIGN TABLE jackson_county_delinquent_tax_parcels (
  fid bigint,
  parcel_number varchar,
  inactive_date varchar,
  delq_yr integer,
  base_delq_amt real,
  taxpayer_name varchar,
  line_care_of varchar,
  mailing_line_1 varchar,
  mailing_line_2 varchar,
  mailing_city varchar,
  mailing_state varchar,
  mailing_zip_code varchar,
  situs_address varchar,
  situs_city varchar,
  situs_zip_code varchar
) SERVER myserver
OPTIONS (layer 'Sheet1');

alter FOREIGN table jackson_county_delinquent_tax_parcels                                OWNER TO c4kc;

\q
EOF
)

echo "${SQL}" | sudo -u postgres psql address_api



/usr/bin/php ./load-jackson-county-tax-delinquency.php -U


#
# Cleanup Foreign Data Wrapper to connect to the CSV file
#
SQL=$(cat <<EOF
-- DROP FOREIGN TABLE jackson_county_delinquent_tax_parcels;
-- DROP SERVER myserver;
\q
EOF
)

echo "${SQL}" | sudo -u postgres psql address_api

