#!/bin/sh
#
# Will need to extract
#

SCRIPT_PATH=`dirname $0`

#
# Create a Foreign Data Wrapper to connect to the CSV file
#
SQL=$(cat <<EOF
--
-- Drop just in case
--
DROP FOREIGN TABLE building_area;
DROP SERVER building_area_server;
--
-- Create
--
CREATE SERVER building_area_server
  FOREIGN DATA WRAPPER file_fdw;



CREATE FOREIGN TABLE building_area (
    id text,
    bldgsqft text,
    kivapin  text) SERVER building_area_server
    OPTIONS ( filename '`pwd`/kcblgdapproxarea.csv', format 'csv' );

alter FOREIGN table building_area OWNER TO c4kc;

\q
EOF
)

echo "Create building_area FWD table\n";
echo "${SQL}" | sudo -u postgres psql address_api


echo "select count(*), kivapin, sum(cast(bldgsqft AS NUMERIC(10,1))) FROM building_area WHERE id <> 'id' GROUP BY kivapin HAVING count(*) > 1 LIMIT 5;" \
| sudo -u postgres psql address_api

echo "Load.php\n";

/usr/bin/php ./load.php -U

echo "Cleanup\n";
#
# Cleanup Foreign Data Wrapper to connect to the CSV file
#
SQL=$(cat <<EOF
DROP FOREIGN TABLE building_area;
DROP SERVER building_area_server;
\q
EOF
)

echo "${SQL}" | sudo -u postgres psql address_api

