#!/bin/sh
#
# Expected to be called by cron
# 55 3 * * * /var/wwwsites/dev-api.codeforkc.org/data/KCMO-Other/load  | mail -s "KCMO-land-bank-parcels" paulb@savagesoft.com 
TEMP_FILE_NAME=/tmp/Other.gdb

SCRIPT_PATH=`dirname $0`
#
# Grab and put the data into a temp file
#

(
   cd /tmp

   rm  -rf $TEMP_FILE_NAME

   curl http://maps.kcmo.org/apps/download/GisDataDownload/Other.gdb.zip > Other.zip
   unzip Other.zip
   rm Other.zip

)

cd $SCRIPT_PATH

sh load-neighborhood-census.sh
sh load-police-divisions.sh
sh load-tif.sh
sh load-vacant-parcels.sh
sh load-council-districts-2001.sh


#
#rm  -rf $TEMP_FILE_NAME
echo "uncomment delete $TEMP_FILE_NAME"


