#!/bin/sh

shp2pgsql -g geom \
 -I /var/wwwsites/address_api.codeforkc.org/data/KCNeighborhoods/KCNeighborhoods.shp \
 address_spatial.kc_nhood_tmp | psql  -d code4kc

exit

Resultes in


   Column   |          Type          |                                 Modifiers                                  
------------+------------------------+----------------------------------------------------------------------------
 gid        | integer                | not null default nextval('address_spatial.kc_nhood_tmp_gid_seq'::regclass)
 name       | character varying(80)  | 
 cartodb_id | integer                | 
 kivapin    | character varying(80)  | 
 landusecod | character varying(80)  | 
 classifica | character varying(80)  | 
 landuse    | character varying(80)  | 
 subclass   | character varying(80)  | 
 geom       | geometry(MultiPolygon) | 
Indexes:
    "kc_nhood_tmp_pkey" PRIMARY KEY, btree (gid)
    "kc_nhood_tmp_geom_gist" gist (geom)


CREATE TABLE address_spatial.mo_kc_city_neighborhoods (
        gid integer NOT NULL,
        name character varying(62),
        geom geometry(MultiPolygon),
        CONSTRAINT pk_kcmo_nhood_gid PRIMARY KEY (gid)
);



CREATE INDEX idx_mo_kc_city_neighborhoods ON
  address_spatial.mo_kc_city_neighborhoods
USING gist(geom);


INSERT INTO address_spatial.mo_kc_city_neighborhoods (gid, name, geom) SELECT gid, name, geom
FROM address_spatial.kc_nhood_tmp;


# lng/lat  

SELECT name FROM address_spatial.mo_kc_city_neighborhoods
WHERE ST_Intersects( ST_MakePoint( -94.5867908690, 39.0903343205), geom);

